window.EMPATHY_DATA = {
  "meta": {
    "title": "Емпатія: люди, які будували концепцію",
    "subtitle": "Хронологія персоналій — від морального почуття та Einfühlung до нейронауки, терапії та критики",
    "generated": "2026-08-13",
    "note": "Рік на таймлайні — опорний момент вкладу в тему емпатії (ключова публікація чи формулювання), а не рік народження.",
    "domains": {
      "moral_philosophy": {
        "label": "Моральна філософія",
        "color": "#c9a227"
      },
      "aesthetics": {
        "label": "Естетика / Einfühlung",
        "color": "#c45c26"
      },
      "phenomenology": {
        "label": "Феноменологія",
        "color": "#7b5ea7"
      },
      "social_theory": {
        "label": "Соціальна теорія",
        "color": "#3d7ea6"
      },
      "clinical": {
        "label": "Терапія та психоаналіз",
        "color": "#1f8a70"
      },
      "developmental": {
        "label": "Психологія розвитку",
        "color": "#3d8b40"
      },
      "social_psych": {
        "label": "Соціальна психологія",
        "color": "#2b6cb0"
      },
      "measurement": {
        "label": "Вимірювання",
        "color": "#0d9488"
      },
      "care_ethics": {
        "label": "Етика турботи",
        "color": "#be185d"
      },
      "neuroscience": {
        "label": "Нейронаука",
        "color": "#c026d3"
      },
      "evolution": {
        "label": "Еволюція / примати",
        "color": "#4d7c0f"
      },
      "literature": {
        "label": "Література та наратив",
        "color": "#b45309"
      },
      "critique": {
        "label": "Критика та сучасність",
        "color": "#57534e"
      },
      "history": {
        "label": "Історія поняття",
        "color": "#78716c"
      }
    }
  },
  "people": [
    {
      "id": "hume",
      "name": "Девід Г'юм",
      "nameOriginal": "David Hume",
      "lived": "1711–1776",
      "year": 1739,
      "yearLabel": "1739–1740",
      "domain": "moral_philosophy",
      "role": "Філософ",
      "place": "Шотландія",
      "keyWork": "A Treatise of Human Nature",
      "contribution": "Симпатія у Г'юма — майже автоматична «комунікація пристрастей»: через подібність та асоціацію ми «підхоплюємо» чужі почуття. На цьому механізмі тримаються моральне схвалення/несхвалення та суспільний зв'язок.",
      "hover": "Заклав модель емоційного зараження: чуже почуття стає нашим через асоціацію, а не через холодний розрахунок."
    },
    {
      "id": "smith",
      "name": "Адам Сміт",
      "nameOriginal": "Adam Smith",
      "lived": "1723–1790",
      "year": 1759,
      "yearLabel": "1759",
      "domain": "moral_philosophy",
      "role": "Філософ та економіст",
      "place": "Шотландія",
      "keyWork": "The Theory of Moral Sentiments",
      "contribution": "Симпатія — зусилля уяви: ми ставимо себе на місце іншого та дивимося очима «безстороннього спостерігача». Це вже не зараження, а перспектива, що лежить в основі пристойності, справедливості та чесноти.",
      "hover": "Переніс акцент із зараження на уявне входження в ситуацію іншого — прямий предок когнітивної емпатії."
    },
    {
      "id": "herder",
      "divider": true,
      "name": "Йоганн Готфрід Гердер",
      "nameOriginal": "Johann Gottfried Herder",
      "lived": "1744–1803",
      "year": 1774,
      "yearLabel": "1770-ті",
      "domain": "social_theory",
      "role": "Філософ культури",
      "place": "Німеччина",
      "keyWork": "Auch eine Philosophie der Geschichte zur Bildung der Menschheit",
      "contribution": "Вимагав «вчування» в чужу епоху, народ і мову, а не суду над ними за власними мірками. Einfühlen стало методом історичного та культурного розуміння.",
      "hover": "Переніс вчування з моралі в герменевтику: зрозуміти іншу культуру — означає увійти в неї, а не міряти своєю."
    },
    {
      "id": "lotze",
      "name": "Герман Лотце",
      "nameOriginal": "Hermann Lotze",
      "lived": "1817–1881",
      "year": 1856,
      "yearLabel": "1856–1864",
      "domain": "aesthetics",
      "role": "Філософ",
      "place": "Німеччина",
      "keyWork": "Mikrokosmos",
      "contribution": "Описав у «Мікрокосмосі» (1856–1864), як спостерігач проеціює власне життєве почуття у форми та простори. Історична передумова для виникнення концепції естетичного Einfühlung у Фішера та Ліппса.",
      "hover": "Сформулював ідею проекції життєвого почуття у форму — важлива передумова до поняття Einfühlung."
    },
    {
      "id": "vischer",
      "name": "Роберт Фішер",
      "nameOriginal": "Robert Vischer",
      "lived": "1847–1933",
      "year": 1873,
      "yearLabel": "1873",
      "domain": "aesthetics",
      "role": "Теоретик естетики",
      "place": "Німеччина",
      "keyWork": "Über das optische Formgefühl",
      "contribution": "Увів термін Einfühlung — «вчування»: спостерігач проектує у форму власну тілесну динаміку й тим самим «оживлює» твір. Точка народження сучасного поняття.",
      "hover": "Саме він у 1873 році дав ім'я Einfühlung: почуття знаходиться не поруч із формою, а всередині неї."
    },
    {
      "id": "dilthey",
      "name": "Вільгельм Дільтей",
      "nameOriginal": "Wilhelm Dilthey",
      "lived": "1833–1911",
      "year": 1900,
      "yearLabel": "1900 / 1910",
      "domain": "social_theory",
      "role": "Філософ наук про дух",
      "place": "Німеччина",
      "keyWork": "Einleitung in die Geisteswissenschaften; Der Aufbau der geschichtlichen Welt",
      "contribution": "Розуміння (Verstehen) та співпереживання (Nacherleben) як метод наук про дух: чуже життя реконструюється з його виражень у пізніх працях 1900–1910-х рр., а не пояснюється за зразком природознавства.",
      "hover": "Обґрунтував співпереживання та вчування як метод гуманітарного пізнання у своїх пізніх працях."
    },
    {
      "id": "lipps",
      "name": "Теодор Ліппс",
      "nameOriginal": "Theodor Lipps",
      "lived": "1851–1914",
      "year": 1903,
      "yearLabel": "1903–1906",
      "domain": "aesthetics",
      "role": "Філософ і психолог",
      "place": "Німеччина",
      "keyWork": "Ästhetik; праці про Einfühlung",
      "contribution": "Систематизував Einfühlung як внутрішню імітацію: ми несвідомо проектуємо кінестетичні та афективні стани на об'єкт або людину. Переніс поняття з чистої естетики в психологію розуміння іншого.",
      "hover": "Зробив Einfühlung загальною психологією: зрозуміти іншого — означає внутрішньо подражувати його стану."
    },
    {
      "id": "worringer",
      "name": "Вільгельм Воррінґер",
      "nameOriginal": "Wilhelm Worringer",
      "lived": "1881–1965",
      "year": 1908,
      "yearLabel": "1908",
      "domain": "aesthetics",
      "role": "Історик мистецтва",
      "place": "Німеччина",
      "keyWork": "Abstraktion und Einfühlung",
      "contribution": "Протиставив емпатію (потяг до органічної форми) та абстракцію (потребу в порядку перед хаосом світу). Показав, що вчування — не універсальний закон мистецтва, а один із двох полюсів.",
      "hover": "Обмежив всевладдя Einfühlung: поруч із вчуванням стоїть абстракція як інша базова установка."
    },
    {
      "id": "titchener",
      "name": "Едвард Тітченер",
      "nameOriginal": "Edward B. Titchener",
      "lived": "1867–1927",
      "year": 1909,
      "yearLabel": "1909",
      "domain": "measurement",
      "role": "Психолог-структураліст",
      "place": "США",
      "keyWork": "Lectures on the Experimental Psychology of the Thought-Processes",
      "contribution": "Увів у американську психологічну літературу 1909 р. термін «empathy» як переклад німецького Einfühlung, пов'язавши його з кінестетичними уявленнями та відтворенням тілесного почуття.",
      "hover": "У 1909 році впровадив у психологічну науку США термін empathy як науковий переклад Einfühlung.",
      "divider": true
    },
    {
      "id": "geiger",
      "name": "Моріц Ґайґер",
      "nameOriginal": "Moritz Geiger",
      "lived": "1880–1937",
      "year": 1911,
      "yearLabel": "1911",
      "domain": "phenomenology",
      "role": "Феноменолог естетики",
      "place": "Німеччина",
      "keyWork": "праці про естетичне Einfühlung",
      "contribution": "Уточнив, що естетичне вчування не тотожне злиттю з об'єктом: існує дистанція споглядання. Важливий коректив до Ліппса всередині феноменології.",
      "hover": "Показав межу естетичної емпатії: вчутися — не означає розчинитися в об'єкті."
    },
    {
      "id": "lee",
      "name": "Вернон Лі (Вайолет Пейджет)",
      "nameOriginal": "Vernon Lee / Violet Paget",
      "lived": "1856–1935",
      "year": 1912,
      "yearLabel": "1912",
      "domain": "aesthetics",
      "role": "Естетик та есеїстка",
      "place": "Велика Британія / Італія",
      "keyWork": "Beauty & Ugliness and Other Studies in Psychological Æsthetics (з C. Anstruther-Thomson)",
      "contribution": "Емпірично фіксувала дихання, позу та м'язове напруження під час споглядання мистецтва. У ключовій праці 1912 року показала естетичну емпатію як тілесний відгук.",
      "hover": "Перша, хто вимірювала естетичну емпатію через тілесні показники: дихання, позу та мускульне напруження."
    },
    {
      "id": "husserl",
      "name": "Едмунд Гуссерль",
      "nameOriginal": "Edmund Husserl",
      "lived": "1859–1938",
      "year": 1912,
      "yearLabel": "1912–1931",
      "domain": "phenomenology",
      "role": "Засновник феноменології",
      "place": "Німеччина / Австрія",
      "keyWork": "Ideen II; Cartesianische Meditationen",
      "contribution": "Емпатія (Einfühlung) у «Ideen II» та «Cartesianische Meditationen» — аналогова аппрезентація: чужа свідомість дана не безпосередньо як моя, а конституюється через тілесне вираження іншого.",
      "hover": "Описав емпатію як аппрезентацію іншого суб'єкта: чуже Я конституюється через тілесність, роблячи світ спільним."
    },
    {
      "id": "scheler",
      "name": "Макс Шелер",
      "nameOriginal": "Max Scheler",
      "lived": "1874–1928",
      "year": 1913,
      "yearLabel": "1913 / 1923",
      "domain": "phenomenology",
      "role": "Феноменолог",
      "place": "Німеччина",
      "keyWork": "Zur Phänomenologie… (1913); Wesen und Formen der Sympathie (1923)",
      "contribution": "Розмежував емоційне зараження, співчуття (Mitgefühl), любов і безпосереднє сприйняття чужого переживання. Сформулював феноменологію симпатії у 1913 р., розширену у 1923 р.",
      "hover": "Склав класичну карту чужих почуттів: розмежував емоційне зараження, співчуття та любов."
    },
    {
      "id": "stein",
      "name": "Едіт Штайн",
      "nameOriginal": "Edith Stein",
      "lived": "1891–1942",
      "year": 1917,
      "yearLabel": "1916 / 1917",
      "domain": "phenomenology",
      "role": "Феноменолог",
      "place": "Німеччина",
      "keyWork": "Zum Problem der Einfühlung",
      "contribution": "Дисертаційна праця у Гуссерля (захист 1916, публікація 1917 «Zum Problem der Einfühlung»): емпатія як невивідний акт сприйняття чужого досвіду sui generis саме як чужого.",
      "hover": "Класична феноменологічна монографія 1917 р.: емпатія — специфічний акт сприйняття досвіду іншого як саме чужого."
    },
    {
      "id": "buber",
      "name": "Мартін Бубер",
      "nameOriginal": "Martin Buber",
      "lived": "1878–1965",
      "year": 1923,
      "yearLabel": "1923",
      "domain": "phenomenology",
      "role": "Філософ діалогу",
      "place": "Австрія / Палестина",
      "keyWork": "Ich und Du",
      "contribution": "Стосунок Я–Ти проти Я–Воно: інший даний не як об'єкт аналізу, а як присутність. Не теорія емпатії, але ключова мова зустрічі, на яку пізніше спиралися терапія та етика турботи.",
      "hover": "Змістив тему з «як я зчитую іншого» на «як я зустрічаю його як Ти, а не як Воно»."
    },
    {
      "id": "taft",
      "name": "Джессі Тафт",
      "nameOriginal": "Jessie Taft",
      "lived": "1882–1960",
      "year": 1933,
      "yearLabel": "1933",
      "domain": "clinical",
      "role": "Філософ, соціальна працівниця",
      "place": "США",
      "keyWork": "The Dynamics of Therapy in a Controlled Relationship",
      "contribution": "У праці 1933 р. описала терапію через стосунок. Разом із В. Робінсон проводила ідеї Отто Ранка (relationship therapy) в США, що стало важливим історичним джерелом для ранньої клієнт-центрованої терапії Роджерса.",
      "hover": "Представниця «функціональної школи»: терапія через стосунок (під впливом О. Ранка), яка вплинула на Роджерса."
    },
    {
      "id": "mead",
      "name": "Джордж Герберт Мід",
      "nameOriginal": "George Herbert Mead",
      "lived": "1863–1931",
      "year": 1934,
      "yearLabel": "1934 (посмертно)",
      "domain": "social_theory",
      "role": "Соціальний філософ",
      "place": "США",
      "keyWork": "Mind, Self, and Society",
      "contribution": "Рольове прийняття (taking the attitude of the other) — умова появи Я, мови та суспільства. Когнітивний каркас того, що пізніше назвуть перспективою / theory of mind.",
      "hover": "Без «прийняття ролі іншого» немає соціального Я. Це соціологічний скелет когнітивної емпатії."
    },
    {
      "id": "merleau",
      "name": "Моріс Мерло-Понті",
      "nameOriginal": "Maurice Merleau-Ponty",
      "lived": "1908–1961",
      "year": 1945,
      "yearLabel": "1945",
      "domain": "phenomenology",
      "role": "Феноменолог",
      "place": "Франція",
      "keyWork": "Phénoménologie de la perception",
      "contribution": "Чужа свідомість зчитується у виразному тілі, а не виводиться силогізмом. Інтертілесність — пряме сприйняття інтенцій. Опора для пізніших теорій «direct perception» емпатії.",
      "hover": "Гнів видно на обличчі та в жесті, а не вираховується. Емпатія як втілене сприйняття, а не теорія."
    },
    {
      "id": "dymond",
      "name": "Розалінд Даймонд Картрайт",
      "nameOriginal": "Rosalind Dymond Cartwright",
      "lived": "1922–2021",
      "year": 1949,
      "yearLabel": "1949",
      "domain": "measurement",
      "role": "Психолог",
      "place": "США",
      "keyWork": "A scale for the measurement of empathic ability",
      "contribution": "Одна з перших операціоналізацій емпатії як точності передбачення думок і почуттів іншого. Переклала філософське поняття у вимірюваний конструкт.",
      "hover": "1949: емпатія вперше стала шкалою — наскільки точно ти вгадуєш внутрішній світ іншого.",
      "divider": true
    },
    {
      "id": "rogers",
      "name": "Карл Роджерс",
      "nameOriginal": "Carl R. Rogers",
      "lived": "1902–1987",
      "year": 1957,
      "yearLabel": "1951 / 1957",
      "domain": "clinical",
      "role": "Гуманістичний психолог",
      "place": "США",
      "keyWork": "Client-Centered Therapy; The Necessary and Sufficient Conditions…",
      "contribution": "Точне емпатичне розуміння — одна з необхідних умов змін. Терапевт відчуває світ клієнта «так, ніби» він був власним, не втрачаючи цього «так, ніби». Установка, а не трюк.",
      "hover": "Зробив емпатію ядром терапії: увійти у рамку клієнта й утримати межу «так, ніби»."
    },
    {
      "id": "greenson",
      "name": "Ральф Ґрінсон",
      "nameOriginal": "Ralph R. Greenson",
      "lived": "1911–1979",
      "year": 1960,
      "yearLabel": "1960",
      "domain": "clinical",
      "role": "Психоаналітик",
      "place": "США",
      "keyWork": "Empathy and its vicissitudes",
      "contribution": "Розібрав емпатію аналітика як тимчасове ототожнення з подальшим поверненням у позицію спостерігача. Описав збої: занадто мало / занадто багато злиття.",
      "hover": "Формула аналітичної емпатії: увійти — і вчасно вийти, інакше це вже не розуміння, а затоплення."
    },
    {
      "id": "barrett-lennard",
      "name": "Ґодвін Барретт-Леннард",
      "nameOriginal": "G. T. Barrett-Lennard",
      "lived": "1926–2023",
      "year": 1962,
      "yearLabel": "1962",
      "domain": "clinical",
      "role": "Психолог",
      "place": "Австралія / Канада",
      "keyWork": "Barrett-Lennard Relationship Inventory",
      "contribution": "Опитувальник сприйнятої емпатії, прийняття та конгруентності у стосунках. Зсув: важлива не «емпатія всередині терапевта», а те, як її відчуває інший.",
      "hover": "Виміряв емпатію з боку отримувача: чи зрозуміли мене — ось критерій, а не самооцінка того, хто допомагає."
    },
    {
      "id": "truax",
      "name": "Чарльз Труакс та Роберт Каркхафф",
      "nameOriginal": "Charles Truax & Robert Carkhuff",
      "lived": "1930-ті–",
      "year": 1967,
      "yearLabel": "1961–1967",
      "domain": "clinical",
      "role": "Дослідники психотерапії",
      "place": "США",
      "keyWork": "Toward Effective Counseling and Psychotherapy",
      "contribution": "Шкали емпатії за Роджерсом, навчання навичці, зв'язок рівня емпатії терапевта із результатом. Емпатія стала тренованою компетенцією допоміжних професій.",
      "hover": "Перевели роджерсівську установку у шкали та тренінги: емпатії можна вчити і її можна міряти під час сесії."
    },
    {
      "id": "hogan",
      "name": "Роберт Гоґан",
      "nameOriginal": "Robert Hogan",
      "lived": "1937–",
      "year": 1969,
      "yearLabel": "1969",
      "domain": "measurement",
      "role": "Психолог особистості",
      "place": "США",
      "keyWork": "Hogan Empathy Scale",
      "contribution": "Шкала емпатії як соціально-когнітивної чутливості та рольового прийняття. Одна з перших широко використовуваних trait-мір.",
      "hover": "Зафіксував емпатію як стійку рису особистості — здатність ставати на точку зору іншого."
    },
    {
      "id": "kohut",
      "name": "Хайнц Когут",
      "nameOriginal": "Heinz Kohut",
      "lived": "1913–1981",
      "year": 1971,
      "yearLabel": "1971 / 1977",
      "domain": "clinical",
      "role": "Психоаналітик, self psychology",
      "place": "США",
      "keyWork": "The Analysis of the Self; The Restoration of the Self",
      "contribution": "Емпатія як «заміщаюча інтроспекція»: і метод збору даних, і лікувальний фактор. Без тривалого перебування у світі пацієнта неможливо зрозуміти порушення Самості.",
      "hover": "У психоаналізі емпатія стала і мікроскопом, і ліками — vicarious introspection."
    },
    {
      "id": "mehrabian",
      "name": "Альберт Меграбян та Норман Епштейн",
      "nameOriginal": "Albert Mehrabian & Norman Epstein",
      "lived": "1939– / —",
      "year": 1972,
      "yearLabel": "1972",
      "domain": "measurement",
      "role": "Психологи",
      "place": "США",
      "keyWork": "A measure of emotional empathy",
      "contribution": "Опитувальник емоційної емпатії: акцент на афективному відгуку, а не на інтелектуальному розумінні. Закріпив розкол когнітивного та афективного вимірів.",
      "hover": "Відділили «я відчуваю з тобою» від «я розумію тебе» — і дали цьому окрему шкалу."
    },
    {
      "id": "hoffman",
      "name": "Мартін Гоффман",
      "nameOriginal": "Martin L. Hoffman",
      "lived": "1929–2016",
      "year": 1975,
      "yearLabel": "1975–2000",
      "domain": "developmental",
      "role": "Психолог розвитку",
      "place": "США",
      "keyWork": "Empathy and Moral Development (2000)",
      "contribution": "Стадії: глобальний дистрес немовляти → егоцентрична емпатія → емпатія до почуттів → до життєвої ситуації та груп. Механізми збудження + зв'язок із провиною, альтруїзмом та упередженістю емпатії.",
      "hover": "Дав онтогенез емпатії й одночасно її моральну ціну: вона плекає добро — і сліпа до далеких.",
      "divider": true
    },
    {
      "id": "meltzoff",
      "name": "Ендрю Мельцофф",
      "nameOriginal": "Andrew N. Meltzoff",
      "lived": "1950–",
      "year": 1977,
      "yearLabel": "1977",
      "domain": "developmental",
      "role": "Психолог розвитку",
      "place": "США",
      "keyWork": "Imitation of facial and manual gestures by human neonates (Science)",
      "contribution": "Дослідження неонатальної імітації (Meltzoff & Moore, 1977) та гіпотеза «like-me»: вроджена тілесна відповідність стала теоретичним фундаментом для подальших моделей розуміння намірів.",
      "hover": "Показав вроджену неонатальну імітацію («ти як я») як тілесне підґрунтя для розвитку соціального пізнання."
    },
    {
      "id": "zahn-waxler",
      "name": "Керолін Зан-Вакслер",
      "nameOriginal": "Carolyn Zahn-Waxler",
      "lived": "1940-ті–",
      "year": 1979,
      "yearLabel": "1979 / 1992",
      "domain": "developmental",
      "role": "Психолог розвитку",
      "place": "США",
      "keyWork": "дослідницька програма (1979); Development of Concern for Others (1992)",
      "contribution": "Систематичне дослідження розвитку турботи про інших у дітей другого року життя (з M. Radke-Yarrow та ін.): походження альтруїстичної поведінки, індивідуальні відмінності та емоційна регуляція.",
      "hover": "Емпірично зафіксувала появу справжньої турботи про іншого на другому році життя дитини."
    },
    {
      "id": "trevarthen",
      "name": "Колвін Тревартен",
      "nameOriginal": "Colwyn Trevarthen",
      "lived": "1931–2024",
      "year": 1979,
      "yearLabel": "1979",
      "domain": "developmental",
      "role": "Психолог немовляцтва",
      "place": "Велика Британія",
      "keyWork": "Communication and cooperation in early infancy",
      "contribution": "Вроджена інтерсуб'єктивність: немовля з перших тижнів перебуває в ритмічному емоційному діалозі. Первинна, потім вторинна інтерсуб'єктивність (~9 міс.) як біологічний корінь емпатії.",
      "hover": "Емпатія не чекає на теорію психічного: вона вже є у проторазмові матері та немовляти."
    },
    {
      "id": "batson",
      "name": "С. Деніел Бетсон",
      "nameOriginal": "C. Daniel Batson",
      "lived": "1943–",
      "year": 1981,
      "yearLabel": "1981–1991",
      "domain": "social_psych",
      "role": "Соціальний психолог",
      "place": "США",
      "keyWork": "The Altruism Question; експерименти empathy–altruism",
      "contribution": "Гіпотеза емпатія–альтруїзм: орієнтована на іншого турбота породжує справді альтруїстичний мотив, а не лише зняття власного дискомфорту. Десятиліття винахідливих експериментів.",
      "hover": "Доводив експериментами: емпатична турбота може спонукати допомогти іншому заради нього самого, а не заради себе."
    },
    {
      "id": "gilligan",
      "name": "Керол Ґілліґан",
      "nameOriginal": "Carol Gilligan",
      "lived": "1936–",
      "year": 1982,
      "yearLabel": "1982",
      "domain": "care_ethics",
      "role": "Психолог моралі",
      "place": "США",
      "keyWork": "In a Different Voice",
      "contribution": "Поруч із етикою справедливості поставила етику турботи та відповідальності, де відгук на конкретного іншого (і емпатична чутливість) — не «недозрілість», а інший голос моралі.",
      "hover": "Повернула в моральну психологію голос стосунків: правильно — це ще й не кинути того, хто поруч."
    },
    {
      "id": "davis",
      "name": "Марк Х. Девіс",
      "nameOriginal": "Mark H. Davis",
      "lived": "1953–",
      "year": 1983,
      "yearLabel": "1980 / 1983",
      "domain": "measurement",
      "role": "Соціальний психолог",
      "place": "США",
      "keyWork": "Interpersonal Reactivity Index (IRI)",
      "contribution": "Чотири шкали: прийняття перспективи, фантазія, емпатична турбота, особистісний дистрес. Стандарт світу: емпатія — не одна риса, а профіль.",
      "hover": "IRI досі є головним опитувальником: чотири різні емпатії в одній людині."
    },
    {
      "id": "noddings",
      "name": "Нел Ноддінґс",
      "nameOriginal": "Nel Noddings",
      "lived": "1929–2022",
      "year": 1984,
      "yearLabel": "1984",
      "domain": "care_ethics",
      "role": "Філософ освіти",
      "place": "США",
      "keyWork": "Caring: A Feminine Approach to Ethics and Moral Education",
      "contribution": "Турбота як engrossment — рецептивна увага до реальності іншого — та зміщення мотивації. Емпатія тут не риса, а етична практика стосунків, зокрема у школі.",
      "hover": "Емпатія як педагогіка: спочатку прийняти реальність учня, потім діяти з неї."
    },
    {
      "id": "stern",
      "name": "Деніел Стерн",
      "nameOriginal": "Daniel N. Stern",
      "lived": "1934–2012",
      "year": 1985,
      "yearLabel": "1985",
      "domain": "developmental",
      "role": "Психоаналітик і дослідник немовляцтва",
      "place": "США / Швейцарія",
      "keyWork": "The Interpersonal World of the Infant",
      "contribution": "Афективна настройка (affect attunement): дорослий відображає не жест, а контур почуття. Так немовля дізнається, що його внутрішнє можна розділити — напередодні емпатії.",
      "hover": "Не повтор руху, а повтор «форми почуття». Настройка — колиска відчуття «мене зрозуміли»."
    },
    {
      "id": "frith",
      "name": "Ута Фріт",
      "nameOriginal": "Uta Frith",
      "lived": "1941–",
      "year": 1985,
      "yearLabel": "1985",
      "domain": "developmental",
      "role": "Когнітивний психолог",
      "place": "Велика Британія",
      "keyWork": "праці про theory of mind та аутизм (з A. Leslie, S. Baron-Cohen)",
      "contribution": "Провідна дослідниця аутизму та Theory of Mind. Застосувала й популяризувала експериментальні парадигми (зокрема тест Саллі–Енн, створений Віммером та Пернером в 1983 р.) для вивчення когнітивної емпатії.",
      "hover": "Закріпила експериментальне вивчення когнітивної емпатії та «теорії розуму» в дослідженнях аутизму."
    },
    {
      "id": "wispe",
      "name": "Лорен Уіспі",
      "nameOriginal": "Lauren Wispé",
      "lived": "1923–1998",
      "year": 1986,
      "yearLabel": "1986 / 1991",
      "domain": "history",
      "role": "Психолог",
      "place": "США",
      "keyWork": "The distinction between sympathy and empathy; The Psychology of Sympathy",
      "contribution": "Історико-понятійне розчищення: sympathy та empathy плутали сто років. Зафіксувала, що це різні традиції, а не синоніми.",
      "hover": "Навела порядок у словнику: співчуття та емпатія — родичі, але не близнюки."
    },
    {
      "id": "eisenberg",
      "name": "Ненсі Айзенберґ",
      "nameOriginal": "Nancy Eisenberg",
      "lived": "1950–",
      "year": 1987,
      "yearLabel": "1980-ті–2000-ні",
      "domain": "developmental",
      "role": "Психолог розвитку",
      "place": "США",
      "keyWork": "праці про емпатію, симпатію та просоціальність",
      "contribution": "Чітко розмежувала емпатію (розділений афект), симпатію (турботу) та особистісний дистрес. Регуляція емоцій визначає, допоможе дитина чи піде в себе.",
      "hover": "Ключове розрізнення поля: розділити почуття ≠ пожаліти ≠ самому поринути в чужому болю."
    },
    {
      "id": "ickes",
      "name": "Вільям Айкс",
      "nameOriginal": "William Ickes",
      "lived": "1947–",
      "year": 1990,
      "yearLabel": "1990 / 1997",
      "domain": "social_psych",
      "role": "Соціальний психолог",
      "place": "США",
      "keyWork": "пародигма empathic accuracy (1990); Everyday Mind Reading (1997)",
      "contribution": "Запровадив парадигму емпатичної точності (empathic accuracy): експериментальне вимірювання того, наскільки вірно зчитуються думки та почуття іншої людини під час живої взаємодії.",
      "hover": "Запровадив вимірювання емпатичної точності: наскільки вірно людина вгадує думки співрозмовника під час діалогу.",
      "divider": true
    },
    {
      "id": "rizzolatti",
      "name": "Джакомо Ріццолатті",
      "nameOriginal": "Giacomo Rizzolatti",
      "lived": "1937–",
      "year": 1992,
      "yearLabel": "1992–1996",
      "domain": "neuroscience",
      "role": "Нейрофізіолог",
      "place": "Італія",
      "keyWork": "відкриття дзеркальних нейронів (група Пармського університету)",
      "contribution": "Очолював дослідницьку групу в Пармі (разом із V. Gallese, L. Fadiga, L. Fogassi та ін.), яка відкрила нейрони премоторної кори макаки, активні при виконанні та спостереженні дії.",
      "hover": "Група в Пармі на чолі з Ріццолатті: нейронний механізм, який активується і при власній дії, і при спостереженні."
    },
    {
      "id": "goleman",
      "name": "Деніел Ґоулман",
      "nameOriginal": "Daniel Goleman",
      "lived": "1946–",
      "year": 1995,
      "yearLabel": "1995",
      "domain": "social_psych",
      "role": "Психолог і популяризатор",
      "place": "США",
      "keyWork": "Emotional Intelligence",
      "contribution": "Вбудував емпатію в масову модель емоційного інтелекту (поруч із самоусвідомленням та регуляцією). Вивів тему з клініки у менеджмент, школу та ЗМІ.",
      "hover": "Зробив емпатію частиною «EQ»: слово вийшло з клініки та філософії у широкий вжиток."
    },
    {
      "id": "baron-cohen",
      "name": "Саймон Барон-Коен",
      "nameOriginal": "Simon Baron-Cohen",
      "lived": "1958–",
      "year": 1995,
      "yearLabel": "1995 / 2003",
      "domain": "developmental",
      "role": "Психолог і дослідник аутизму",
      "place": "Велика Британія",
      "keyWork": "Mindblindness; The Essential Difference; Empathy Quotient",
      "contribution": "Когнітивна vs афективна емпатія; mindblindness при аутизмі; теорія емпатизація–систематизація; EQ. Емпатія як вимірюваний профіль індивідуальних відмінностей.",
      "hover": "Розвів «зрозуміти думку» та «розділити почуття» і прив'язав це до аутизму, статі та EQ."
    },
    {
      "id": "dewaal",
      "name": "Франс де Вааль",
      "nameOriginal": "Frans de Waal",
      "lived": "1948–2024",
      "year": 1996,
      "yearLabel": "1996 / 2009",
      "domain": "evolution",
      "role": "Приматолог",
      "place": "Нідерланди / США",
      "keyWork": "Good Natured; The Age of Empathy; Russian-doll model",
      "contribution": "Втіха, цілеспрямована допомога, зараження у приматів. Модель «мотрійки»: від зараження до перспективи. Мораль виростає з емпатії тварин, а не проти неї.",
      "hover": "Довів у шимпанзе та слонів те, що філософії здавалося людським: утішити того, кому боляче."
    },
    {
      "id": "zahavi",
      "name": "Дан Захаві",
      "nameOriginal": "Dan Zahavi",
      "lived": "1967–",
      "year": 1999,
      "yearLabel": "1999 / 2005",
      "domain": "phenomenology",
      "role": "Феноменолог",
      "place": "Данія",
      "keyWork": "Self and Other (2005); праці про феноменологію емпатії",
      "contribution": "Повернув феноменологічний доробок Гуссерля та Штайн у сучасні дискусії з нейронаукою: емпатія дає прямий доступ до вираження іншого при збереженні його інакшості.",
      "hover": "Нагадав нейронауці феноменологічний принцип: емпатія дає чужий досвід саме як чужий, без злиття."
    },
    {
      "id": "nussbaum",
      "name": "Марта Нуссбаум",
      "nameOriginal": "Martha C. Nussbaum",
      "lived": "1947–",
      "year": 2001,
      "yearLabel": "2001 / 2013",
      "domain": "moral_philosophy",
      "role": "Філософ",
      "place": "США",
      "keyWork": "Upheavals of Thought; Political Emotions",
      "contribution": "Співчуття як судження про чуже страждання, незаслуженість та власну вразливість. Література та мистецтво розширюють коло тих, кого ми здатні пожаліти політично.",
      "hover": "Співчуття — не сире почуття, а думка плюс уява. Роман навчає політичної емпатії."
    },
    {
      "id": "gallese",
      "name": "Вітторіо Ґаллезе",
      "nameOriginal": "Vittorio Gallese",
      "lived": "1959–",
      "year": 2001,
      "yearLabel": "2001 / 2003",
      "domain": "neuroscience",
      "role": "Нейробіолог",
      "place": "Італія",
      "keyWork": "The Shared Manifold Hypothesis; embodied simulation",
      "contribution": "Втілена симуляція: базова емпатія як спільний простір («shared manifold») дій, емоцій та відчуттів. Пов'язав дзеркала з інтерсуб'єктивністю та естетикою.",
      "hover": "Перевів дзеркальні нейрони на мову емпатії: ми не вираховуємо іншого — ми його тілесно симулюємо."
    },
    {
      "id": "halpern",
      "name": "Джоді Галперн",
      "nameOriginal": "Jodi Halpern",
      "lived": "1960-ті–",
      "year": 2001,
      "yearLabel": "2001",
      "domain": "clinical",
      "role": "Лікар та філософ медицини",
      "place": "США",
      "keyWork": "From Detached Concern to Empathy",
      "contribution": "Проти ідеалу «відстороненої турботи» лікаря: клінічна емпатія — залучена уява конкретного пацієнта, а не сентиментальність чи холодний професіоналізм.",
      "hover": "Повернула лікарю право (і обов'язок) уявляти, як воно цьому хворому — без розчинення в ньому."
    },
    {
      "id": "fonagy",
      "name": "Пітер Фонаґі",
      "nameOriginal": "Peter Fonagy",
      "lived": "1952–",
      "year": 2002,
      "yearLabel": "2002",
      "domain": "clinical",
      "role": "Психоаналітик",
      "place": "Велика Британія",
      "keyWork": "Affect Regulation, Mentalization, and the Development of the Self",
      "contribution": "Менталізація: здатність бачити себе та іншого в термінах внутрішніх станів. Клінічний спадкоємець емпатії та ToM, опора MBT.",
      "hover": "Перейменував клінічний досвід емпатії у mentalizing: утримувати розум у собі та в іншому, коли боляче."
    },
    {
      "id": "preston",
      "name": "Стефані Престон",
      "nameOriginal": "Stephanie D. Preston",
      "lived": "1970-ті–",
      "year": 2002,
      "yearLabel": "2002",
      "domain": "evolution",
      "role": "Психолог",
      "place": "США",
      "keyWork": "Empathy: Its ultimate and proximate bases (з de Waal, BBS)",
      "contribution": "Perception–Action Model: сприйняття стану іншого автоматично активує ті самі репрезентации; регуляція вирішує, чи буде допомога, дистрес або холодність.",
      "hover": "Одна стаття-рамка на 20 років уперед: емпатія = сприйняття → спільний стан → (іноді) турбота."
    },
    {
      "id": "decety",
      "name": "Жан Десеті",
      "nameOriginal": "Jean Decety",
      "lived": "1960–",
      "year": 2004,
      "yearLabel": "2000-ні–2010-ті",
      "domain": "neuroscience",
      "role": "Соціальний нейронауковець",
      "place": "Франція / США",
      "keyWork": "fMRI/EEG праці про емпатію до болю, моралі, психопатії",
      "contribution": "Розвів мережі афективного поділу (острівець, ACC) та когнітивної перспективи; роль розрізнення Я–інший. Розвиток, клініка, справедливість.",
      "hover": "Картограф емпатії в мозку: де ми відчуваємо чужий біль — і де утримуємо, що це не наш."
    },
    {
      "id": "singer",
      "name": "Таня Зінґер",
      "nameOriginal": "Tania Singer",
      "lived": "1969–",
      "year": 2004,
      "yearLabel": "2004 / 2010-ті",
      "domain": "neuroscience",
      "role": "Нейронауковиця",
      "place": "Німеччина",
      "keyWork": "Empathy for pain involves the affective but not sensory components of pain (Science, 2004)",
      "contribution": "fMRI-дослідження у Science (2004) показало, що емпатія до болю залучає частково перекриваючі афективні (але не сенсорні) компоненти нейронного опрацювання болю. Згодом розмежувала емпатію та співчуття.",
      "hover": "Показала, що спостереження чужого болю активує афективні зони мозку; згодом розмежувала емпатію та співчуття."
    },
    {
      "id": "gallagher",
      "name": "Шон Ґаллахер",
      "nameOriginal": "Shaun Gallagher",
      "lived": "1948–",
      "year": 2005,
      "yearLabel": "2001–2005",
      "domain": "phenomenology",
      "role": "Філософ, енактивізм",
      "place": "США",
      "keyWork": "How the Body Shapes the Mind; interaction theory",
      "contribution": "Критика і симуляції, і теорії: у живому взаємозв'язку ми часто напряму сприймаємо емоції та наміри. Емпатія — втілена інтеракція, а не внутрішній театр.",
      "hover": "У діалозі емпатія не в голові, а між тілами: ми бачимо злість, а не вираховуємо її."
    },
    {
      "id": "goldman",
      "name": "Елвін Ґолдман",
      "nameOriginal": "Alvin I. Goldman",
      "lived": "1938–",
      "year": 2006,
      "yearLabel": "1989 / 2006",
      "domain": "phenomenology",
      "role": "Філософ свідомості",
      "place": "США",
      "keyWork": "Simulating Minds",
      "contribution": "Теорія симуляції: ми розуміємо іншого, проганяючи його стани на власній ментальній моделі. Філософський каркас і для дзеркал, і для «стати на місце».",
      "hover": "Формально описав те, що Ліппс відчував: зрозуміти іншого — запустити його програму на своєму процесорі."
    },
    {
      "id": "stueber",
      "name": "Карстен Штюбер",
      "nameOriginal": "Karsten Stueber",
      "lived": "1960-ті–",
      "year": 2006,
      "yearLabel": "2006",
      "domain": "phenomenology",
      "role": "Філософ",
      "place": "Німеччина / США",
      "keyWork": "Rediscovering Empathy",
      "contribution": "Захистив реактивовуючу емпатію як незамінний спосіб розуміти раціонального агента — проти чисто теоретичної folk psychology. Повернув емпатію в методологію гуманітарних наук.",
      "hover": "Сказав теорії розуму: без емпатичного програвання причин іншого агента ви сліпі."
    },
    {
      "id": "vignemont",
      "name": "Фредерік де Віньмон",
      "nameOriginal": "Frédérique de Vignemont",
      "lived": "1970-ті–",
      "year": 2006,
      "yearLabel": "2006 / 2016",
      "domain": "phenomenology",
      "role": "Філософ",
      "place": "Франція",
      "keyWork": "статті про емпатію, тіло та self–other (зокрема з T. Singer)",
      "contribution": "Аналітична навігація: зараження / емпатія / симпатія; коли спільні репрезентації недостатні; роль тіла та контролю. Міст філософії та сканера.",
      "hover": "Розплутала терміни для нейронауковців: спільне почуття ще не є емпатією, доки ти знаєш, що це не ти."
    },
    {
      "id": "slote",
      "name": "Майкл Слот",
      "nameOriginal": "Michael Slote",
      "lived": "1941–",
      "year": 2007,
      "yearLabel": "2007 / 2010",
      "domain": "care_ethics",
      "role": "Моральний філософ",
      "place": "США",
      "keyWork": "The Ethics of Care and Empathy",
      "contribution": "Побудував нормативну етику, в якій емпатія — критерій моральної оцінки дій та інститутів, а не лише психологічний факт.",
      "hover": "Переніс емпатію з психології в норму: вчинок хороший, якщо виростає з емпатичного відгуку."
    },
    {
      "id": "keen",
      "name": "Сюзан Кін",
      "nameOriginal": "Suzanne Keen",
      "lived": "1960-ті–",
      "year": 2007,
      "yearLabel": "2007",
      "domain": "literature",
      "role": "Літературознавиця",
      "place": "США",
      "keyWork": "Empathy and the Novel",
      "contribution": "Наративна емпатія: як форма роману (фокалізація, персонаж) викликає вчування — і чому це не гарантує мораль у реальному житті.",
      "hover": "Запитала чесно: якщо роман вчить жаліти, чому читачі не стають автоматично добрішими?"
    },
    {
      "id": "rutsch",
      "name": "Едвін Ратш",
      "nameOriginal": "Edwin Rutsch",
      "lived": "1962–",
      "year": 2007,
      "yearLabel": "2007–2011",
      "domain": "social_theory",
      "role": "Розробник Емпатійних кіл",
      "place": "США",
      "keyWork": "CultureOfEmpathy.com; Емпатійні кола (Empathy Circles)",
      "contribution": "Творець прикладного формату «Емпатичні кола» (Empathy Circles) — структурованої практики активного слухання для розрядки конфліктів і ведення діалогу. Засновник міжнародного руху Culture of Empathy та величезного відеоархіву інтерв'ю про емпатію.",
      "hover": "Перетворив емпатію з теоретичної концепції на практичну інженерну технологію діалогу та зняття суспільної напруги."
    },
    {
      "id": "iacoboni",
      "name": "Марко Якобоні",
      "nameOriginal": "Marco Iacoboni",
      "lived": "1960-ті–",
      "year": 2008,
      "yearLabel": "2008",
      "domain": "neuroscience",
      "role": "Нейробіолог",
      "place": "США",
      "keyWork": "Mirroring People",
      "contribution": "Один із головних інтерпретаторів та популяризаторів концепції дзеркальних нейронів людини. Узагальнив дані fMRI-досліджень щодо імітації, соціального зв'язку та емпатії у праці «Mirroring People» (2008).",
      "hover": "Узагальнив і популяризував дослідження дзеркальної системи людини та її зв'язок із соціальним пізнанням."
    },
    {
      "id": "breithaupt",
      "name": "Фріц Брайтгаупт",
      "nameOriginal": "Fritz Breithaupt",
      "lived": "1967–",
      "year": 2009,
      "yearLabel": "2009 / 2017",
      "domain": "literature",
      "role": "Германіст / когнітивіст культури",
      "place": "Німеччина / США",
      "keyWork": "Kulturen der Empathie; Die dunklen Seiten der Empathie",
      "contribution": "Емпатія як культурна та наративна машина вибору сторони. Темні сторони: поляризація, садистське співпереживання жертві через насильство, блокування третього.",
      "hover": "Показав, як емпатія обирає «наших» і може розпалювати конфлікт, а не гасити його."
    },
    {
      "id": "rifkin",
      "name": "Джеремі Ріфкін",
      "nameOriginal": "Jeremy Rifkin",
      "lived": "1945–",
      "year": 2009,
      "yearLabel": "2009",
      "domain": "critique",
      "role": "Соціальний теоретик",
      "place": "США",
      "keyWork": "The Empathic Civilization",
      "contribution": "Великий наратив: історія цивілізації як розширення емпатичного кола (сім'я → нація → біосфера) на тлі енергетичних режимів. Популяризація макроісторії емпатії.",
      "hover": "Намалював цивілізацію як зростаюче коло «своїх»: від крові до виду — якщо встигнемо до кризи."
    },
    {
      "id": "tomasello",
      "name": "Майкл Томаселло",
      "nameOriginal": "Michael Tomasello",
      "lived": "1950–",
      "year": 2009,
      "yearLabel": "1999–2009",
      "domain": "evolution",
      "role": "Психолог і приматолог",
      "place": "США / Німеччина",
      "keyWork": "Why We Cooperate; The Cultural Origins of Human Cognition",
      "contribution": "Досліджував спільну інтенційність (shared intentionality), спільну увагу та кооперацію у малюків порівняно з приматами як унікальний шлях людського культурного розвитку.",
      "hover": "Показав спільну інтенційність та кооперацію малюків як біологічну й культурну основу людського «ми»."
    },
    {
      "id": "keysers",
      "name": "Крістіан Кейзерс",
      "nameOriginal": "Christian Keysers",
      "lived": "1973–",
      "year": 2011,
      "yearLabel": "2004–2011",
      "domain": "neuroscience",
      "role": "Нейробіолог",
      "place": "Нідерланди",
      "keyWork": "The Empathic Brain",
      "contribution": "Дзеркальність не лише дій, а й дотику, емоцій, відчуттів. Соціальний мозок як система спільних репрезентацій.",
      "hover": "Показав: ми дзеркалимо не лише жест — біль, дотик, огида теж живуть у спільних картах."
    },
    {
      "id": "lamm",
      "name": "Клаус Ламм",
      "nameOriginal": "Claus Lamm",
      "lived": "1973–",
      "year": 2011,
      "yearLabel": "2007–2010-ті",
      "domain": "neuroscience",
      "role": "Нейронауковець",
      "place": "Австрія",
      "keyWork": "метааналізи емпатії до болю; self–other distinction",
      "contribution": "Уточнив мережі емпатії до болю, пластичність, роль контролю та розрізнення Я/інший. Міст між Зінґер, Десеті та філософією механізмів.",
      "hover": "Зібрав розрізнені скани у стійку картину: які вузли дійсно є спільними при чужому болю."
    },
    {
      "id": "prinz",
      "name": "Джессі Прінц",
      "nameOriginal": "Jesse J. Prinz",
      "lived": "1973–",
      "year": 2011,
      "yearLabel": "2011",
      "domain": "critique",
      "role": "Філософ",
      "place": "США",
      "keyWork": "Is Empathy Necessary for Morality?",
      "contribution": "Аргумент, що мораль спирається скоріше на емоції наразок гніву та огиди до несправедливості, ніж на емпатію. Емпатія ані необхідна, ані достатня.",
      "hover": "Зняв з емпатії корону морального почуття: можна бути справедливим, не влазячи в чужу шкуру.",
      "divider": true
    },
    {
      "id": "coplan",
      "name": "Емі Коплан",
      "nameOriginal": "Amy Coplan",
      "lived": "1970-ті–",
      "year": 2011,
      "yearLabel": "2011",
      "domain": "phenomenology",
      "role": "Філософ",
      "place": "США",
      "keyWork": "Empathy: Philosophical and Psychological Perspectives (ред. з P. Goldie)",
      "contribution": "Звузила визначення: емпатія вимагає афективного відповідності + чіткого розрізнення Я/інший. Зібрала міждисциплінарний канон 2010-х.",
      "hover": "Поставила фільтр: якщо ти не відрізняєш своє почуття від чужого — це ще не емпатія."
    },
    {
      "id": "krznaric",
      "name": "Роман Кржнарич",
      "nameOriginal": "Roman Krznaric",
      "lived": "1970-ті–",
      "year": 2014,
      "yearLabel": "2014",
      "domain": "critique",
      "role": "Філософ-популяризатор",
      "place": "Велика Британія / Австралія",
      "keyWork": "Empathy: A Handbook for Revolution",
      "contribution": "Емпатія як громадянська навичка та політичний інструмент: вийти зі свого бульбашки, практикувати «експериментальне» життя іншого. Музей емпатії.",
      "hover": "Перевів академічну тему у практику: емпатія як революція повсякденних звичок погляду."
    },
    {
      "id": "jamison",
      "name": "Леслі Джеймісон",
      "nameOriginal": "Leslie Jamison",
      "lived": "1983–",
      "year": 2014,
      "yearLabel": "2014",
      "domain": "literature",
      "role": "Есеїстка",
      "place": "США",
      "keyWork": "The Empathy Exams",
      "contribution": "Літературна феноменологія емпатії: робота «пацієнтом» для студентів-медиків, межі чужого розуміння, спокуса красиво страждати за іншого.",
      "hover": "Перевірила емпатію на собі: чи можна натренувати розуміння болю — і де це стає виставою."
    },
    {
      "id": "bloom",
      "name": "Пол Блум",
      "nameOriginal": "Paul Bloom",
      "lived": "1963–",
      "year": 2016,
      "yearLabel": "2016",
      "domain": "critique",
      "role": "Психолог",
      "place": "США / Канада",
      "keyWork": "Against Empathy: The Case for Rational Compassion",
      "contribution": "Аргументував у праці «Against Empathy» (2016), що емоційна (афективна) емпатія упереджена й короткозора, тому для моральних та політичних рішень краще керуватися раціональним співчуттям.",
      "hover": "Висунув концептуальну критику афективної емпатії як морального орієнтиру на користь раціонального співчуття."
    },
    {
      "id": "lanzoni",
      "name": "Сьюзан Ланцони",
      "nameOriginal": "Susan Lanzoni",
      "lived": "1960-ті–",
      "year": 2018,
      "yearLabel": "2018",
      "domain": "history",
      "role": "Історик науки",
      "place": "США",
      "keyWork": "Empathy: A History",
      "contribution": "Перша повна історія мандрів слова: від естетики лабораторій та музеїв через терапію, соцопитування та нейронауку. Показала, що «емпатія» — не вічна сутність, а мінливий інструмент.",
      "hover": "Зібрала всю генеалогію слова: хто, коли та навіщо перевинайшов empathy."
    }
  ]
};
